name: Sync Fork

on:
  schedule:
    - cron: '0 8 * * 1' 
  workflow_dispatch:  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "AlvinSetyaPranata"
          git config --global user.email "comand.alvin@gmail.com"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/original-author/repository.git || true
          git fetch upstream
          git checkout feat/file-form-enhancement
          git merge upstream/feat/file-form-enhancement --allow-unrelated-histories || true
          git push origin feat/file-form-enhancement